### ISSUE TITLE
6-move win for FUNKY

### ISSUE THREAD

**Issue by fkodom** [TylerGlaiel/wordlebot#3]
Hi! Just left a comment on your [Medium article](https://medium.com/@tglaiel/the-mathematically-optimal-first-guess-in-wordle-cbcb03c19b0a) 😊. I think there might be a problem with your benchmark script? Or maybe a typo in reporting the results in your article. I've found that your solver gives a 6-move solution for FUNKY, using ROATE as the starting word:

<img width="328" alt="Screen Shot 2022-02-05 at 9 05 56 PM" src="https://user-images.githubusercontent.com/45951340/152666250-80d9f4d0-00a8-4881-a1b7-5862846648b8.png">

Your article cited a maximum of 5 moves for ROATE. Do you know if there's an issue with the benchmarking script?

Thanks!

**Comment by TylerGlaiel** [comment]
you guessed 2 starter words (roate AND raise) instead of just 1 of them for some reason

**Comment by fkodom** [comment]
Got it -- thanks for the clarification!  Guess I misunderstood how to use the program.
