### ISSUE TITLE
cycles on ARILS

### ISSUE THREAD

**Issue by forgottenbutnotgone** [TylerGlaiel/wordlebot#4]
If I enter the following It cycles ad infinitum

RAISE
bbbbg

ARILS
bbbbb
...

ARILS
bbbbb

**Comment by TylerGlaiel** [comment]
type "x" not "b", not sure what its doing when you type b instead...

**Comment by forgottenbutnotgone** [comment]
Thanks, my mistake. I should have looked more closely.
